# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowWorkWithDBTables.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowWorkWithDBTables(object):
    def setupUi(self, WindowWorkWithDBTables):
        WindowWorkWithDBTables.setObjectName("WindowWorkWithDBTables")
        WindowWorkWithDBTables.resize(778, 336)
        self.centralwidget = QtWidgets.QWidget(WindowWorkWithDBTables)
        self.centralwidget.setObjectName("centralwidget")
        self.ComboBoxCurrentDBTable = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBoxCurrentDBTable.setGeometry(QtCore.QRect(100, 10, 191, 22))
        self.ComboBoxCurrentDBTable.setEditable(False)
        self.ComboBoxCurrentDBTable.setCurrentText("Проекты")
        self.ComboBoxCurrentDBTable.setObjectName("ComboBoxCurrentDBTable")
        self.ComboBoxCurrentDBTable.addItem("")
        self.ComboBoxCurrentDBTable.addItem("")
        self.ComboBoxCurrentDBTable.addItem("")
        self.ComboBoxCurrentDBTable.addItem("")
        self.ComboBoxCurrentDBTable.addItem("")
        self.ComboBoxCurrentDBTable.addItem("")
        self.ComboBoxCurrentDBTable.addItem("")
        self.ComboBoxCurrentDBTable.addItem("")
        self.TableWidgetDBTableData = QtWidgets.QTableWidget(self.centralwidget)
        self.TableWidgetDBTableData.setGeometry(QtCore.QRect(10, 40, 591, 231))
        self.TableWidgetDBTableData.setObjectName("TableWidgetDBTableData")
        self.TableWidgetDBTableData.setColumnCount(0)
        self.TableWidgetDBTableData.setRowCount(0)
        self.PushButtonLogOut = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonLogOut.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.PushButtonLogOut.setObjectName("PushButtonLogOut")
        self.ComboBoxIdMutableNote = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBoxIdMutableNote.setEnabled(False)
        self.ComboBoxIdMutableNote.setGeometry(QtCore.QRect(310, 10, 81, 22))
        self.ComboBoxIdMutableNote.setObjectName("ComboBoxIdMutableNote")
        self.PushButtonDoExtion = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonDoExtion.setEnabled(False)
        self.PushButtonDoExtion.setGeometry(QtCore.QRect(410, 10, 191, 23))
        self.PushButtonDoExtion.setObjectName("PushButtonDoExtion")
        self.RadioButtonInsertNote = QtWidgets.QRadioButton(self.centralwidget)
        self.RadioButtonInsertNote.setEnabled(False)
        self.RadioButtonInsertNote.setGeometry(QtCore.QRect(630, 50, 101, 17))
        self.RadioButtonInsertNote.setObjectName("RadioButtonInsertNote")
        self.RadioButtonEditNote = QtWidgets.QRadioButton(self.centralwidget)
        self.RadioButtonEditNote.setEnabled(False)
        self.RadioButtonEditNote.setGeometry(QtCore.QRect(630, 110, 111, 17))
        self.RadioButtonEditNote.setObjectName("RadioButtonEditNote")
        self.RadioButtonDeleteNote = QtWidgets.QRadioButton(self.centralwidget)
        self.RadioButtonDeleteNote.setEnabled(False)
        self.RadioButtonDeleteNote.setGeometry(QtCore.QRect(630, 180, 101, 17))
        self.RadioButtonDeleteNote.setObjectName("RadioButtonDeleteNote")
        self.LabelTitleOperations = QtWidgets.QLabel(self.centralwidget)
        self.LabelTitleOperations.setGeometry(QtCore.QRect(610, 10, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelTitleOperations.setFont(font)
        self.LabelTitleOperations.setObjectName("LabelTitleOperations")
        self.TextEditWorkspace = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditWorkspace.setEnabled(False)
        self.TextEditWorkspace.setGeometry(QtCore.QRect(10, 280, 761, 31))
        self.TextEditWorkspace.setObjectName("TextEditWorkspace")
        self.PushButtonInsertSeparator = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonInsertSeparator.setGeometry(QtCore.QRect(650, 230, 75, 23))
        self.PushButtonInsertSeparator.setObjectName("PushButtonInsertSeparator")
        self.PushButtonInsertSeparator.setEnabled(False)
        WindowWorkWithDBTables.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(WindowWorkWithDBTables)
        self.statusbar.setObjectName("statusbar")
        WindowWorkWithDBTables.setStatusBar(self.statusbar)

        self.retranslateUi(WindowWorkWithDBTables)
        QtCore.QMetaObject.connectSlotsByName(WindowWorkWithDBTables)

    def retranslateUi(self, WindowWorkWithDBTables):
        _translate = QtCore.QCoreApplication.translate
        WindowWorkWithDBTables.setWindowTitle(_translate("WindowWorkWithDBTables", "SC: Window work with tables"))
        self.ComboBoxCurrentDBTable.setItemText(0, _translate("WindowWorkWithDBTables", "Проекты"))
        self.ComboBoxCurrentDBTable.setItemText(1, _translate("WindowWorkWithDBTables", "Договоры"))
        self.ComboBoxCurrentDBTable.setItemText(2, _translate("WindowWorkWithDBTables", "Технические задания"))
        self.ComboBoxCurrentDBTable.setItemText(3, _translate("WindowWorkWithDBTables", "Заказчики"))
        self.ComboBoxCurrentDBTable.setItemText(4, _translate("WindowWorkWithDBTables", "Услуги"))
        self.ComboBoxCurrentDBTable.setItemText(5, _translate("WindowWorkWithDBTables", "Сотрудники"))
        self.ComboBoxCurrentDBTable.setItemText(6, _translate("WindowWorkWithDBTables", "Проектные команды"))
        self.ComboBoxCurrentDBTable.setItemText(7, _translate("WindowWorkWithDBTables", "Аккаунты"))
        self.PushButtonLogOut.setText(_translate("WindowWorkWithDBTables", "LogOut"))
        self.PushButtonDoExtion.setText(_translate("WindowWorkWithDBTables", "Выполнить действие"))
        self.RadioButtonInsertNote.setText(_translate("WindowWorkWithDBTables", "Новая запись"))
        self.RadioButtonEditNote.setText(_translate("WindowWorkWithDBTables", "Изменить запись"))
        self.RadioButtonDeleteNote.setText(_translate("WindowWorkWithDBTables", "Удалить запись"))
        self.LabelTitleOperations.setText(_translate("WindowWorkWithDBTables", "Выберите тип опирации:"))
        self.PushButtonInsertSeparator.setText(_translate("WindowWorkWithDBTables", "$_%_$"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowWorkWithDBTables = QtWidgets.QMainWindow()
    ui = Ui_WindowWorkWithDBTables()
    ui.setupUi(WindowWorkWithDBTables)
    WindowWorkWithDBTables.show()
    sys.exit(app.exec_())
